[CSA-CP] Update WiseConnect to v3.3.3
SiliconLabsSoftware/matter_sdk pull request #56
Opened 2024-10-17 09:40 UTC by arun-silabs

This PR contains the changes required for updating WiseConnect to 3.3.3.

2024-10-17 17:53 UTC, mykrupp commented on .gitmodules
> -	branch = v3.3.2
This isn't necessary to do in matter_sdk, if we want to do this update it should be done in CSA. We use the wifi_sdk from the matter_extension, so we can still comeplete the task to move to 3.3.3 by updating matter_extensions wifi_sdk submodule.

2024-10-17 17:55 UTC, mykrupp commented on third_party/silabs/matter_support
Same comment on this, these should only be updated in CSA.

2024-10-17 17:55 UTC, mykrupp commented on third_party/silabs/wifi_sdk
Same comment on this, these should only be updated in CSA.

2024-10-18 02:37 UTC, mkardous-silabs requested changes
@arun-silabs We can still cherry-pick changes to th  matter v1.4 branch. Instead of a cherry-pick PR, please open a PR to port these changes to CSA v1.4 branch once the PR towards master is merged.

2024-10-23 03:49 UTC, closed without merging